ARG NGC_VERSION=23.11-py3
FROM nvcr.io/nvidia/pytorch:${NGC_VERSION} AS base

FROM base as base-dev
RUN mkdir -p /run/sshd
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt install -y tmux \
  openssh-server \
  zstd \
  nload \
  iftop \
  git-lfs \
  ansible \
  aria2 \
  default-jdk \
  fio \
  iputils-ping \
  perftest \
  tcpdump \
  iperf \
  iproute2 \
  libibverbs-dev \
  ibverbs-utils \
  infiniband-diags \
  htop \
  socat \
  rlwrap \
  net-tools \
  sudo

FROM base-dev as nccl-tests
COPY --from=base-dev / /
RUN git clone https://github.com/NVIDIA/nccl-tests.git /opt/nccl-tests && cd /opt/nccl-tests && make MPI=1 MPI_HOME=/opt/hpcx/ompi -j

FROM nccl-tests as py310
COPY --from=nccl-tests /opt/nccl-tests /opt/nccl-tests
COPY requirements ./requirements
COPY requirements.txt ./
RUN /usr/bin/python -c "import torch; print(torch.__version__)"
RUN --mount=type=cache,target=/root/.cache/pip \
  /usr/bin/python -m pip install -r requirements.txt

FROM py310 as common-software-updates
ENV TZ Asia/Shanghai
ENV NCCL_IB_RETRY_CNT "13"
ENV NCCL_IB_TIMEOUT "22"
ENV NCCL_DEBUG "WARN"
